backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master) 

media_folder: "public/images/uploads"
media_libray: 
  name: uploads
public_folder: "/images"

collections:
  # - name: "blog" # Used in routes, e.g., /admin/collections/blog
  #   label: "Blog" # Used in the UI
  #   folder: "_posts/blog" # The path to the folder where the documents are stored
  #   create: true # Allow users to create new documents in this collection
  #   slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  #   fields: # The fields for each document, usually in front matter
  #     - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
  #     - {label: "Title", name: "title", widget: "string"}
  #     - {label: "Date", name: "date", widget: "datetime"}
  #     - {label: "Featured Image", name: "thumbnail", widget: "image"}
  #     - {label: "Body", name: "body", widget: "markdown"}

  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "site/content/home.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
      - label: "Resume Page"
        name: "resume"
        file: "site/content/resume.yml"
        fields:
          - {label: Title, name: title, widget: string}
      - label: "Portfolio Page"
        name: "portfolio"
        file: "site/content/portfolio.yml"
        fields:
          - {label: Title, name: title, widget: string}

  # - label: "Carousel Images"
  #   name: "carousel images"
  #   file: "site/content/home.yml"
  #   widget: "image"
  #   folder: "public/images"
  #   choose_url: true
  #   media_library:
  #     config:
  #       multiple: true

  - label: "Education"
    name: "education"
    folder: "site/content/education"
    create: true
    widget: "list"
    fields:
      - {label: "College", name: college, widget: string, default: "University or College"}
      - {label: "Program", name: program, widget: string, default: "e.g., MBA"}
      - {label: "Image", name: "thumbnail", widget: "image"}
