backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/images/uploads"
media_libray:
  name: uploads
public_folder: "/images"

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "site/content/home.yml"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
      - label: "Resume Page"
        name: "resume"
        file: "site/content/resume.yml"
        fields:
          - { label: Title, name: title, widget: string }
      - label: "Portfolio Page"
        name: "portfolio"
        file: "site/content/portfolio.yml"
        fields:
          - { label: Title, name: title, widget: string }

  - label: "Carousel Images"
    name: "carousel images"
    file: "site/content/home.yml"
    widget: "image"
    folder: "public/images"
    choose_url: true
    media_library:
      config:
        multiple: true

  - label: "Education"
    name: "education"
    folder: "site/content/education"
    create: true
    widget: "list"
    add_to_top: true
    fields:
      - {
          label: "College",
          name: college,
          widget: string,
          default: "University or College",
        }
      - {
          label: "Program",
          name: program,
          widget: string,
          default: "e.g., MBA",
        }
      - { label: "Image", name: "companyThumbnail", widget: "image" }

  - label: "Work History"
    name: "workHistory"
    folder: "site/content/workHistory"
    create: true
    widget: "list"
    add_to_top: true
    fields:
      - {
          label: "Company",
          name: company,
          widget: string,
          default: "ACME, Inc",
        }
      - { label: "Company Image", name: "companyThumbnail", widget: "image" }
      - {
          label: "Company URL",
          name: companyURL,
          widget: string,
          default: "www.acme.com",
        }
      - {
          label: "Location",
          name: companyLocation,
          widget: string,
          default: "Boston or Remote",
        }
      - {
          label: "Dates Employed",
          name: companyDates,
          widget: string,
          default: "March 2020-Present",
        }
      - {label: "Work Bullets",
        name: workBullets,
        widget: list,
        field:
          - {
              label: "Work Bullet",
              name: workBullet,
              widget: string,
              default: "Responsible for Being Awesome",
            }}
